version: '3.8'

services:
  db:
    image: postgres:16-alpine
    container_name: iluminacity_db
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: iluminacity_db
    volumes:
      - pg_data:/var/lib/postgresql/data
    restart: always
    networks:
      - iluminacity_network

  adminer:
    image: adminer
    container_name: iluminacity_adminer
    ports:
      - "8080:8080"
    environment:
      ADMINER_DEFAULT_SERVER: db
    depends_on:
      - db
    networks:
      - iluminacity_network

volumes:
  pg_data:

networks:
  iluminacity_network: